version: '3.8'

services:

  db:
    image: postgres
    container_name: trainsysdb
    build:
      context: ./db
    environment:
      POSTGRES_DB: trainsysdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
    restart: always